name: Piensa Dulce Madrid
favicon: null
layout_spectrum: 0.27254
typography_spectrum: 0.07652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edddc3'
    - '#8ab2e3'
    - '#0d1215'
    - '#40424e'
    - '#606745'
  brandStrength: 0.875
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
